import React from 'react';
import { VideoMetadata } from '../types';

interface MetadataDisplayProps {
  metadata: VideoMetadata | null;
  selectedFile?: File | null;
  extractSubtitle?: (file: File, streamIndex: number, language?: string, codecName?: string, isForced?: boolean) => Promise<void>;
  extractStream?: (file: File, streamIndex: number, streamType: string, codecName?: string) => Promise<void>;
  extractAllSubtitles?: (file: File) => Promise<void>;
}

export const MetadataDisplay: React.FC<MetadataDisplayProps> = ({ metadata, selectedFile, extractSubtitle, extractStream, extractAllSubtitles }) => {
  if (!metadata) return null;

  // Generate comprehensive metadata text for copying
  const generateMetadataText = (): string => {
    let text = '=== VIDEO METADATA ===\n\n';
    
    // Format Information
    text += '--- FORMAT INFORMATION ---\n';
    if (metadata.format) {
      Object.entries(metadata.format).forEach(([key, value]) => {
        if (value && value !== 'unknown' && value !== 'N/A') {
          const label = key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
          text += `${label}: ${value}\n`;
        }
      });
    }
    text += '\n';
    
    // All Streams
    text += '--- STREAMS ---\n';
    metadata.streams?.forEach((stream, index) => {
      const streamType = stream.codec_type.toUpperCase();
      text += `\n${streamType} Stream ${index + 1}:\n`;
      text += `  Index: ${stream.index !== undefined ? stream.index : index}\n`;
      text += `  Codec: ${stream.codec_name}\n`;
      
      if (stream.codec_long_name) text += `  Codec Long Name: ${stream.codec_long_name}\n`;
      if (stream.profile) text += `  Profile: ${stream.profile}\n`;
      if (stream.duration) text += `  Duration: ${stream.duration}\n`;
      
      // Stream-specific information
      if (stream.codec_type === 'video') {
        const videoStream = stream as any;
        if (videoStream.width && videoStream.height) text += `  Resolution: ${videoStream.width}x${videoStream.height}\n`;
        if (videoStream.r_frame_rate) text += `  Frame Rate: ${parseFrameRate(videoStream.r_frame_rate)}\n`;
        if (videoStream.pix_fmt) text += `  Pixel Format: ${videoStream.pix_fmt}\n`;
        if (videoStream.bit_rate && videoStream.bit_rate !== 'unknown') text += `  Bitrate: ${Math.round(parseInt(videoStream.bit_rate) / 1000)} kbps\n`;
        if (videoStream.nb_frames) text += `  Total Frames: ${videoStream.nb_frames}\n`;
      } else if (stream.codec_type === 'audio') {
        const audioStream = stream as any;
        if (audioStream.sample_rate) text += `  Sample Rate: ${audioStream.sample_rate} Hz\n`;
        if (audioStream.channels) text += `  Channels: ${audioStream.channels}\n`;
        if (audioStream.channel_layout) text += `  Channel Layout: ${audioStream.channel_layout}\n`;
        if (audioStream.bit_rate && audioStream.bit_rate !== 'unknown') text += `  Bitrate: ${Math.round(parseInt(audioStream.bit_rate) / 1000)} kbps\n`;
      } else if (stream.codec_type === 'subtitle') {
        const subtitleStream = stream as any;
        if (subtitleStream.language) text += `  Language: ${subtitleStream.language}\n`;
        if (subtitleStream.title) text += `  Title: ${subtitleStream.title}\n`;
        text += `  Default: ${subtitleStream.default ? 'Yes' : 'No'}\n`;
        text += `  Forced: ${subtitleStream.forced ? 'Yes' : 'No'}\n`;
      }
      
      if (stream.codec_tag) text += `  Codec Tag: ${stream.codec_tag}\n`;
      if (stream.codec_tag_string) text += `  Codec Tag String: ${stream.codec_tag_string}\n`;
    });
    
    text += '\n=== END METADATA ===\n';
    text += `Generated by OpenSubtitles Video Metadata Extractor\n`;
    text += `File: ${selectedFile?.name || 'Unknown'}\n`;
    text += `Date: ${new Date().toISOString()}\n`;
    
    return text;
  };

  // Copy metadata to clipboard
  const copyMetadataToClipboard = async () => {
    try {
      const metadataText = generateMetadataText();
      await navigator.clipboard.writeText(metadataText);
      
      // Show success feedback
      const button = document.getElementById('copy-metadata-btn');
      if (button) {
        const originalText = button.textContent;
        button.textContent = 'Copied!';
        button.classList.add('bg-green-600');
        button.classList.remove('bg-blue-600', 'hover:bg-blue-700');
        
        setTimeout(() => {
          button.textContent = originalText;
          button.classList.remove('bg-green-600');
          button.classList.add('bg-blue-600', 'hover:bg-blue-700');
        }, 2000);
      }
    } catch (error) {
      console.error('Failed to copy metadata:', error);
      // Fallback for older browsers
      const textArea = document.createElement('textarea');
      textArea.value = generateMetadataText();
      document.body.appendChild(textArea);
      textArea.select();
      document.execCommand('copy');
      document.body.removeChild(textArea);
    }
  };

  const formatFileSize = (bytes: string): string => {
    const size = parseInt(bytes);
    if (size === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(size) / Math.log(k));
    return parseFloat((size / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
  };

  const parseFrameRate = (frameRate: string): string => {
    if (!frameRate) return 'N/A';
    const [num, den] = frameRate.split('/').map(Number);
    return den ? `${(num / den).toFixed(2)} fps` : 'N/A';
  };

  const MetadataItem: React.FC<{ title: string; data: Record<string, string>; priority?: boolean }> = ({ title, data, priority = false }) => {
    // Filter out N/A, empty, null, undefined, and unknown values
    const filteredData = Object.entries(data).filter(([_, value]) => 
      value !== '' && 
      value !== null && 
      value !== undefined && 
      value !== 'N/A' && 
      value !== 'unknown'
    );
    
    // Don't render if no data to show
    if (filteredData.length === 0) return null;
    
    return (
      <div className={`
        border rounded-lg shadow-sm overflow-hidden mb-4
        ${priority ? 'border-orange-400 bg-orange-50' : 'border-gray-200 bg-white'}
      `}>
        <div className={`
          px-4 py-3 border-b border-gray-200
          ${priority ? 'bg-orange-500 text-white' : 'bg-gray-100 text-gray-800'}
        `}>
          <h3 className="font-semibold text-xs uppercase tracking-wide">
            {title}
          </h3>
        </div>
        <div className="p-4 space-y-3">
          {filteredData.map(([key, value]) => (
            <div key={key} className="flex justify-between items-center">
              <span className="text-gray-600 text-sm font-medium">{key}:</span>
              <span className={`
                font-mono text-sm font-semibold
                ${priority ? 'text-orange-700' : 'text-gray-900'}
              `}>
                {value}
              </span>
            </div>
          ))}
        </div>
      </div>
    );
  };

  // Check if we should show the Extract All Subtitles button
  const subtitleStreams = metadata.streams?.filter(stream => stream.codec_type === 'subtitle') || [];
  const showExtractAllButton = selectedFile && extractAllSubtitles && subtitleStreams.length > 0 && 
    (selectedFile.name.toLowerCase().endsWith('.mkv') || selectedFile.name.toLowerCase().endsWith('.webm'));

  const handleExtractAllSubtitles = async () => {
    if (selectedFile && extractAllSubtitles) {
      await extractAllSubtitles(selectedFile);
    }
  };

  return (
    <div id="video-metadata-results" className="mt-8">
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-3xl font-bold text-gray-800">Video Metadata</h2>
        {showExtractAllButton && (
          <button
            onClick={handleExtractAllSubtitles}
            className="bg-purple-600 hover:bg-purple-700 text-white px-6 py-3 rounded-lg shadow-lg transition-colors font-semibold text-lg"
            title={`Extract all ${subtitleStreams.length} subtitle tracks as ZIP`}
          >
            Extract All Subtitles ({subtitleStreams.length})
          </button>
        )}
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        

        {/* Format Information */}
        {metadata.format && (
          <div className="border border-gray-200 bg-white rounded-lg shadow-sm overflow-hidden mb-4">
            <div className="px-4 py-3 border-b border-gray-200 bg-gray-100 text-gray-800 flex justify-between items-center">
              <h3 className="font-semibold text-xs uppercase tracking-wide">
                Format Information
              </h3>
              <button
                id="copy-metadata-btn"
                onClick={copyMetadataToClipboard}
                className="bg-blue-600 hover:bg-blue-700 text-white px-3 py-1 rounded text-xs font-medium transition-colors flex items-center gap-1"
                title="Copy all metadata to clipboard"
              >
                <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                </svg>
                Copy Metadata
              </button>
            </div>
            <div className="p-4 space-y-3">
              {Object.entries({
                ...(metadata.format.format_name && { 'Format': metadata.format.format_name }),
                ...(metadata.format.duration && { 'Duration': metadata.format.duration }),
                ...(metadata.format.size && { 'Size': formatFileSize(metadata.format.size) }),
                ...(metadata.format.bit_rate && metadata.format.bit_rate !== 'unknown' && { 
                  'Bitrate': `${Math.round(parseInt(metadata.format.bit_rate) / 1000)} kbps` 
                }),
                ...(metadata.format.fps && metadata.format.fps !== 'unknown' && { 
                  'FPS': `${parseFloat(metadata.format.fps).toFixed(2)} fps` 
                }),
                ...(metadata.format.movietimems && metadata.format.movietimems !== 'unknown' && { 
                  'Movie Time (ms)': `${parseInt(metadata.format.movietimems).toLocaleString()} ms` 
                }),
                ...(metadata.format.movieframes && metadata.format.movieframes !== 'unknown' && { 
                  'Movie Frames': `${parseInt(metadata.format.movieframes).toLocaleString()} frames` 
                })
              }).map(([key, value]) => (
                <div key={key} className="flex justify-between items-center">
                  <span className="text-gray-600 text-sm font-medium">{key}:</span>
                  <span className="text-gray-900 text-sm font-mono bg-gray-50 px-2 py-1 rounded">
                    {value}
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Stream Information */}
        {metadata.streams?.map((stream, index) => {
          const streamType = stream.codec_type.charAt(0).toUpperCase() + stream.codec_type.slice(1);
          const streamInfo: Record<string, string> = {
            'Index': stream.index !== undefined ? stream.index.toString() : index.toString(),
            'Type': streamType,
            ...(stream.codec_name && { 'Codec': stream.codec_name }),
            ...(stream.profile && { 'Profile': stream.profile })
          };


          if (stream.codec_type === 'video') {
            if (stream.width && stream.height) {
              streamInfo['Resolution'] = `${stream.width}x${stream.height}`;
              streamInfo['Width'] = stream.width.toString();
              streamInfo['Height'] = stream.height.toString();
            }
            if (stream.r_frame_rate) {
              const frameRate = parseFrameRate(stream.r_frame_rate);
              if (frameRate !== 'N/A') streamInfo['Frame Rate'] = frameRate;
            }
            if (stream.avg_frame_rate) {
              const avgFrameRate = parseFrameRate(stream.avg_frame_rate);
              if (avgFrameRate !== 'N/A') streamInfo['Avg Frame Rate'] = avgFrameRate;
            }
            if (stream.pix_fmt) streamInfo['Pixel Format'] = stream.pix_fmt;
            if (stream.bit_rate && stream.bit_rate !== 'unknown') {
              streamInfo['Bitrate'] = `${Math.round(parseInt(stream.bit_rate) / 1000)} kbps`;
            }
            if (stream.duration) streamInfo['Duration'] = stream.duration;
            if (stream.nb_frames) streamInfo['Frame Count'] = stream.nb_frames;
            if (stream.level) streamInfo['Level'] = stream.level;
            if (stream.codec_tag) streamInfo['Codec Tag'] = stream.codec_tag;
            if (stream.codec_tag_string) streamInfo['Codec Tag String'] = stream.codec_tag_string;
            if (stream.codec_long_name) streamInfo['Codec Long Name'] = stream.codec_long_name;
          } else if (stream.codec_type === 'audio') {
            if (stream.sample_rate) streamInfo['Sample Rate'] = `${stream.sample_rate} Hz`;
            if (stream.channels) streamInfo['Channels'] = stream.channels.toString();
            if (stream.channel_layout) streamInfo['Channel Layout'] = stream.channel_layout;
            if (stream.bit_rate && stream.bit_rate !== 'unknown') {
              streamInfo['Bitrate'] = `${Math.round(parseInt(stream.bit_rate) / 1000)} kbps`;
            }
            if (stream.duration) streamInfo['Duration'] = stream.duration;
            if (stream.codec_tag) streamInfo['Codec Tag'] = stream.codec_tag;
            if (stream.codec_tag_string) streamInfo['Codec Tag String'] = stream.codec_tag_string;
            if (stream.codec_long_name) streamInfo['Codec Long Name'] = stream.codec_long_name;
          } else if (stream.codec_type === 'subtitle') {
            if (stream.language) streamInfo['Language'] = stream.language;
            if (stream.title) streamInfo['Title'] = stream.title;
            streamInfo['Default'] = stream.default ? 'Yes' : 'No';
            streamInfo['Forced'] = stream.forced ? 'Yes' : 'No';
            if (stream.size && stream.size !== 'unknown') {
              streamInfo['Size'] = formatFileSize(stream.size);
            }
            if (stream.duration) streamInfo['Duration'] = stream.duration;
            if (stream.codec_tag) streamInfo['Codec Tag'] = stream.codec_tag;
            if (stream.codec_tag_string) streamInfo['Codec Tag String'] = stream.codec_tag_string;
            if (stream.codec_long_name) streamInfo['Codec Long Name'] = stream.codec_long_name;
          }

          const handleDownloadSubtitle = async () => {
            if (selectedFile && extractSubtitle && stream.codec_type === 'subtitle' && stream.index !== undefined) {
              await extractSubtitle(selectedFile, stream.index, stream.language, stream.codec_name, stream.forced);
            }
          };


          const handleDownloadStream = async () => {
            const streamIndex = stream.index !== undefined ? stream.index : index;
            
            if (selectedFile && extractStream && (stream.codec_type === 'video' || stream.codec_type === 'audio')) {
              await extractStream(selectedFile, streamIndex, stream.codec_type, stream.codec_name);
            }
          };

          return (
            <div key={index} className="relative">
              <MetadataItem
                title={`${streamType} Stream ${index + 1}`}
                data={streamInfo}
              />
              {stream.codec_type === 'subtitle' && selectedFile && extractSubtitle && (
                <div className="absolute top-2 right-2 flex gap-1">
                  <button
                    onClick={handleDownloadSubtitle}
                    className="bg-blue-500 hover:bg-blue-600 text-white text-xs px-2 py-1 rounded shadow-sm transition-colors"
                    title="Extract subtitle from this stream"
                  >
                    Extract subtitles
                  </button>
                </div>
              )}
              {(stream.codec_type === 'video' || stream.codec_type === 'audio') && selectedFile && extractStream && (
                <button
                  onClick={handleDownloadStream}
                  className="absolute top-2 right-2 bg-green-500 hover:bg-green-600 text-white text-xs px-2 py-1 rounded shadow-sm transition-colors"
                  title={`Extract ${stream.codec_type} stream`}
                >
                  Extract {stream.codec_type === 'video' ? 'Video' : 'Audio'}
                </button>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
};